# Generated by Django 5.1 on 2024-08-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='name',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='Criculum_level',
            field=models.CharField(choices=[('TVET_LEVEL_1', 'TVET_1'), ('TVET_LEVEL_2', 'TVET_2'), ('TVET_LEVEL_3', 'TVET_3'), ('TVET_LEVEL_4', 'TVET_4'), ('TVET_LEVEL_5', 'TVET_5'), ('DIPLOMA', 'DIPLOMA')], default='TVET_LEVEL_1', max_length=255),
        ),
    ]
