# Generated by Django 5.1 on 2024-08-08 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_curriculum_name_curriculum_criculum_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='included_course', to='course.course'),
            preserve_default=False,
        ),
    ]
