# Generated by Django 5.1 on 2024-08-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_lesson_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseLesson',
        ),
    ]
