# Generated by Django 5.1 on 2024-08-08 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentassignmentsubmit',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='assignment.assignment'),
        ),
        migrations.AddField(
            model_name='studentassignmentsubmit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
